name: GuiClassSelection
version: 8.0.0
main: me.teamethereal.Arcania.Main
description: Class selection gui for Arcania
author: TacticalShroom
api-version: 1.16
commands:
  class:
    description: gui for class selection
  excalibur:
    description: gives the player excalibur
  compendium:
    description: gives the player a compendium
  staff:
    description: sets the player in staff mode
  spawnwand:
    description: gives the player a spawnwand
  questCreate:
    description: creates the specified quest
  party:
    description: a series of commands to join/leave/create/invite/disband parties
    aliases: p